# ============================================================
# AI AGENT MODULE
# This file creates a LangGraph-based AI agent that can:
# 1. Use different LLM providers (Gemini or OpenAI)
# 2. Optionally perform web search using Tavily
# 3. Return the final AI response to the backend API
# ============================================================

# ------------------------------------------------------------
# Optional: Load environment variables from .env file
# Only required if you are NOT using pipenv or system env vars
# ------------------------------------------------------------
# from dotenv import load_dotenv
# load_dotenv()

# ------------------------------------------------------------
# Step 1: Load API Keys from Environment Variables
# These keys are required for the LLM providers and search tool
# ------------------------------------------------------------
import os

GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")   # Gemini API Key
TAVILY_API_KEY = os.environ.get("TAVILY_API_KEY")   # Tavily Web Search API Key
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")   # OpenAI API Key


# ------------------------------------------------------------
# Step 2: Import LLMs and External Tools
# Gemini and OpenAI are the supported LLM providers
# Tavily is used to allow the agent to perform web searches
# ------------------------------------------------------------
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI
from langchain_community.tools.tavily_search import TavilySearchResults

# Default LLM instances (used if needed)
openai_llm = ChatOpenAI(model="gpt-4o-mini")
gemini_llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")

# Tavily search tool configuration
search_tool = TavilySearchResults(max_results=2)


# ------------------------------------------------------------
# Step 3: Import LangGraph Agent Builder
# create_react_agent builds a ReAct-style reasoning agent
# The agent can think, decide to use tools, and respond
# ------------------------------------------------------------

# from langgraph.prebuilt import create_react_agent
from langchain.agents import create_react_agent
from langchain_core.messages.ai import AIMessage


# ------------------------------------------------------------
# Default system prompt
# This defines the personality and behavior of the AI agent
# It can be overridden from the frontend UI
# ------------------------------------------------------------
system_prompt = "Act as an AI chatbot who is smart and friendly"


# ============================================================
# MAIN AGENT EXECUTION FUNCTION
# This function is called by the FastAPI backend
# ============================================================
def get_response_from_ai_agent(llm_id, query, allow_search, system_prompt, provider):
    """
    Creates and runs an AI agent based on user configuration.

    Parameters
    ----------
    llm_id : str
        The model name selected by the user (e.g. gemini-2.5-flash)

    query : list[str]
        The user message list sent from the frontend

    allow_search : bool
        Enables or disables the Tavily search tool

    system_prompt : str
        Defines the behavior/personality of the AI agent

    provider : str
        Specifies which LLM provider to use (Gemini or OpenAI)

    Returns
    -------
    str
        Final response generated by the AI agent
    """

    # --------------------------------------------------------
    # Step 1: Select LLM provider dynamically
    # --------------------------------------------------------
    if provider == "Gemini":
        llm = ChatGoogleGenerativeAI(model=llm_id)

    elif provider == "OpenAI":
        llm = ChatOpenAI(model=llm_id)

    else:
        raise ValueError("Unsupported model provider")


    # --------------------------------------------------------
    # Step 2: Configure tools for the agent
    # If web search is enabled, Tavily is added as a tool
    # Otherwise, the agent runs without external tools
    # --------------------------------------------------------
    tools = [TavilySearchResults(max_results=2)] if allow_search else []


    # --------------------------------------------------------
    # Step 3: Create the LangGraph ReAct Agent
    # The agent can reason, call tools, and produce responses
    # --------------------------------------------------------
    agent = create_react_agent(
        model=llm,
        tools=tools,
        state_modifier=system_prompt
    )


    # --------------------------------------------------------
    # Step 4: Prepare agent input state
    # LangGraph agents operate on a "messages state"
    # --------------------------------------------------------
    state = {"messages": query}


    # --------------------------------------------------------
    # Step 5: Execute the agent
    # The agent may reason, call tools, and produce messages
    # --------------------------------------------------------
    
    # response = agent.invoke(state)
    try:
        response = agent.invoke(state)
    except Exception as e:
        return {"error": str(e)}


    # --------------------------------------------------------
    # Step 6: Extract AI messages from the response
    # LangGraph returns multiple messages (system, user, AI)
    # We only extract the final AI response
    # --------------------------------------------------------
    messages = response.get("messages")

    ai_messages = [
        message.content
        for message in messages
        if isinstance(message, AIMessage)
    ]


    # --------------------------------------------------------
    # Step 7: Return the final AI-generated response
    # --------------------------------------------------------
#    return ai_messages[-1]
    return {"response": ai_messages[-1]}
